version: '3.3'

services:
  menu-service:
    restart: unless-stopped
    build: .
    ports:
      # localhost:docker
      - "9105:9105"
    depends_on:
      - menu-db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    entrypoint: sh -c "menu-service migrate up && menu-service run service"


  menu-db:
    image: postgres
    restart: always
    ports:
      # localhost:docker
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local