openapi: 3.0.0
info:
  version: 1.0.0
  title: menu-service
  description: ''
servers:
  - url: 'https://api.demo.cafe-service'
    description: menu-service Developer Environment
security:
  - bearerAuth: []