-- +migrate Up

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer generated by default as identity
    primary key,
    category_name character varying COLLATE pg_catalog."default" NOT NULL,
    unit character varying COLLATE pg_catalog."default" NOT NULL
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.categories
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.meals
(
    id integer generated by default as identity
    primary key,
    position_name character varying COLLATE pg_catalog."default" NOT NULL,
    category_id integer NOT NULL,
    price double precision NOT NULL,
    amount double precision NOT NULL,
    CONSTRAINT categories FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.meals
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.receipts
(
    id integer generated by default as identity
    primary key,
    meal_id integer NOT NULL,
    ingredient_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT meal FOREIGN KEY (meal_id)
    REFERENCES public.meals (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.receipts
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.menus
(
    id integer generated by default as identity
    primary key,
    cafe_id integer NOT NULL
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.menus
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.meal_menus
(
    id integer generated by default as identity
    primary key,
    meal_id integer NOT NULL,
    menu_id integer NOT NULL,
    CONSTRAINT meal_menu_meal_fkey FOREIGN KEY (meal_id)
    REFERENCES public.meals (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT meal_menu_menu_fkey FOREIGN KEY (menu_id)
    REFERENCES public.menus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.meal_menus
    OWNER to postgres;

-- +migrate Down

DROP TABLE IF EXISTS public.meal_menus;
DROP TABLE IF EXISTS public.menus;
DROP TABLE IF EXISTS public.receipts;
DROP TABLE IF EXISTS public.meals;
DROP TABLE IF EXISTS public.categories;
